---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: latest
  customize:
    memory: 384

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
  run_list:
  - recipe[rackspace_apt]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box
- name: debian-7.2.0
  driver_config:
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
  run_list:
  - recipe[rackspace_apt]

suites:
- name: default
  run_list:
  - recipe[rackspace_user]
  - recipe[minitest-handler]
  attributes:
    rackspace_user:
      rack_user:
        password_hash: "$6$J0bAE8By$MzIJ2XkfdNoon/0GTKpNjybgq6uToblJoXFwDhdUXmYWh/V5b4fdYv7PeYSVWRW2xw99F086AVdNnUi115OnE."

- name: additional_users
  run_list:
  - recipe[rackspace_user::additional_users]
  - recipe[minitest-handler]
  attributes:
    rackspace_user:
      users:
        test_user1:
          password: "$6$J0bAE8By$MzIJ2XkfdNoon/0GTKpNjybgq6uToblJoXFwDhdUXmYWh/V5b4fdYv7PeYSVWRW2xw99F086AVdNnUi115OnE."
          note: "Test User 1"
          home: "/home/test_user1"
          shell: "/bin/bash"
          enabled: true
          manage_home: true
          authorized_keys: 
            ["ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAtzhEm/e1iABdN/Ciba49/cCJ8w8S18x/U6DMXruV3Vlc99+LNJlgRfTg+dNxAN8dxv/cfhQzOWMj9uM3TPHU/iq323CCCrM+SA0aESzuuYoXDmfV0urq9bBdmJFq0KcfECM6Hzu2Bm8kaUkPwZjE3n4QAuw9P+SE3y6WDXeq+EM= test_user1@example.com"]

- name: rack_user
  run_list:
  - recipe[rackspace_user::rack_user]
  - recipe[minitest-handler]
  attributes: {}
